title: "Joseph Owuor Owino"
description: "Mathematical Analysis | Operator Theory"
url: "https://josephowuorowino.github.io"
baseurl: ""

theme: minima
markdown: kramdown

author:
  name: Joseph Owuor Owino
  email: josephowuorowino@gmail.com

header_pages:
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - contact.md

plugins:
  - jekyll-seo-tag
Add site configuration
